### ISSUE TITLE
Load .r3d files in Python

### ISSUE THREAD

**Issue by Haydnspass** [marek-simonik/record3d#24]
Hey,

If I understand it correctly ".r3d" files contain all RGBD information. Is it possible to load them via the python API or is there a small snipped you could provide on how to load those? Currently, I export to .mp4 but as I understand it, the quality is not optimal here and files are pretty large.

**Comment by marek-simonik** [comment]
Hi,
the `.r3d`  are ordinary ZIP files, so the easiest way to access the RGBD data is to unzip a `.r3d` file and then read the individual frames. In Python, the RGB images can be loaded e.g. by `cv2.imread()` and here is a snippet that shows how to load the depth files: https://github.com/marek-simonik/record3d/issues/7#issuecomment-736573410

> the quality is not optimal here and files are pretty large.

Yes, the depth accuracy is worse due to mp4 compression, but the mp4 files are quite small compared to `.r3d`.

I assume the information above answered your question, so I am closing this issue, but feel free to ask follow-up questions :).
