### ISSUE TITLE
Visual Code window pop up

### ISSUE THREAD

**Issue by sonoshrmsi** [marek-simonik/record3d#26]
Dear Marek, your library is amazing. I wanna use this LiDar data for my university project for obstacle avoidance for truck platooning (prototypes). Is it possible to extract the point data from your library to use it in my control algorithm?  

Best,
Shahryar

**Comment by marek-simonik** [comment]
Hello Shahryar,

thank you :). Yes, it is possible to obtain point data using this library. You can do it by unprojecting the depth images using the [provided intrinsic matrix](https://github.com/marek-simonik/record3d/blob/7a3764ba0e516e7905dafe9f413dd8f13955f4ce/demo-main.py#L52) similarly to how I do it [here](https://github.com/marek-simonik/record3d_unity_streaming/blob/f9d5cdb33db815dc55e77cb12e2c740d89432b7e/Record3DUnityStreaming.cpp#L111).

Since we are already in contact over email, I am closing this issue. But we can of course continue our discussion either in this thread or over email in case you would have any follow-up questions.

Thanks,
Marek
