### ISSUE TITLE
program crash

### ISSUE THREAD

**Issue by weiyizhi** [marek-simonik/record3d#3]
Connected to pydev debugger (build 183.4588.64)
Searching for devices
1 device(s) found
	ID: 4779
	UDID: ..

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

I try to use the python version in Mac and Linux. But the same problem occurred.

**Comment by marek-simonik** [comment]
Hello @weiyizhi ,
this crashing is caused by mismatch in the version of the Record3D iOS app and this library. Please update to iOS 14, update to the latest version of Record3D and use the latest version of this library.

Refer to the following issue for more details and for an alternative solution: https://github.com/marek-simonik/record3d/issues/2
