### ISSUE TITLE
Problem export zip PLY

### ISSUE THREAD

**Issue by mickatt** [marek-simonik/record3d#35]
Hello Marek

I recorded 1 hour before some 3D videos with Record3D app and when I got home I wanted to export in ABC PLY format but I only have 4kb files with no info I see thumbnails of my videos in the library but I can't read them
how do i really need these videos
Please help me

**Comment by marek-simonik** [comment]
Hello,

I apologize for this issue — the first thing that I thought could cause this is low amount of disk space; may I ask how much free disk space do you have on your iPhone/iPad? I do NOT recommend exporting into ABC, because the file size would be enormous for a hour-long 3D Video (maybe in the order of TB [sic]).

The most size-efficient export format is "*Sequence of glTF meshes*" (note that it produces meshes, not point clouds).

If you would need to export a very long video, then I would maybe recommend exporting it in parts (the Settings tab > Export options > enable Customize export time range).

Can we please continue our discussion over email at support@record3d.app ? I think I will be able to respond faster via email than via Github. Thank you.
