### ISSUE TITLE
About depth map

### ISSUE THREAD

**Issue by HquGhy** [marek-simonik/record3d#54]
Whether the python file in the demo needs to be modified in order to obtain the depth map？

**Comment by marek-simonik** [comment]
I'm not sure if I understood your question. The Python demo does already give access to the depth map: https://github.com/marek-simonik/record3d/blob/d8637f57702faa6224c27550ab2b689791f9ac50/demo-main.py#L50

**Comment by HquGhy** [comment]
I mean, I want a depth map in png format

**Comment by marek-simonik** [comment]
If you want to save the depth map [provided in the Python demo](https://github.com/marek-simonik/record3d/blob/d8637f57702faa6224c27550ab2b689791f9ac50/demo-main.py#L50) into PNG format, then you will have to do it yourself by modifying the code according to your needs, because the Python demo does not have such capability (the demo is meant just to illustrate how to use the API).
