### ISSUE TITLE
Get frame timestamp in usb stream

### ISSUE THREAD

**Issue by VimalMollyn** [marek-simonik/record3d#91]
Hi, thanks for creating such an awesome project! I was wondering if you could provide timestamps for each frame while streaming over USB? Something like the swift unix timestamp `NSDate().timeIntervalSince1970` would be wonderful ([link](https://developer.apple.com/documentation/foundation/date/1780353-init)).

**Comment by marek-simonik** [comment]
Hi,

since Record3D 1.10.3, the `miscData` buffer contains an ASCII-encoded JSON string (note that it is **not** `NULL`-terminated) in the format `{ "metadata": { "relativeTimestamp": 0.0, "unixTimestampOnReceivedFrame": 0.0 } }`.

`relativeTimestamp` is a relative time in seconds, at which the camera hardware captured that frame. It is not a UNIX timestamp.

`unixTimestampOnReceivedFrame` is the `NSDate().timeIntervalSince1970` called in the camera callback when a new frame is received. Please note that it is **NOT** the UNIX timestamp of the moment when the camera hardware captured the frame. The difference between two consecutive `relativeTimestamp` and the difference between two consecutive `unixTimestampOnReceivedFrame` will therefore not be the same. In my opinion, `unixTimestampOnReceivedFrame` is useless for obtaining exact timings, but I included it since you insisted.
