### ISSUE TITLE
Support for VisionOS/AVP

### ISSUE THREAD

**Issue by Gaaaavin** [marek-simonik/record3d#92]
Does the project have any future plan to add support to VisionOS and to be used on AVP?
That would be excited as I know the lidar from AVP is much more powerful than iPhone and iPad.
As a computer vision researcher, I'd love to see if it's possible to get those data directly from AVP.

**Comment by marek-simonik** [comment]
There is no plan to add support for visionOS at the moment, because to the best of my knowledge, Apple does not provide an API that would allow developers to access LiDAR depth data, [as communicated by an Apple Vision Pro Engineer on the Developer Forums](https://developer.apple.com/forums/thread/731434?answerId=755561022#755561022) (if this isn't true anymore, please let me know).

Moreover, Apple only sells AVP in a few select countries, so I would not be able to buy it because Apple does not sell it where I live.
