### ISSUE TITLE
How can obtain perFrameIntrinsicCoeffs from demo-main.py code?

### ISSUE THREAD

**Issue by jeonhuhuhu** [marek-simonik/record3d#99]
Thank you for your hard work in providing a good app.

I receive and save data in real time in the `demo-main.py` code. 

However, although necessary values ​​such as Poses, Frametimestamps, fps, initPose, h, w, dh, dw, K, etc. are loaded and used, data called `perFrameIntrinsicCoeffs` exists in the metadata generated by the Recorded3D app. 

I am curious about where the **`perFrameIntrinsicCoeffs`** data can be retrieved and how to save and obtain it.

**Comment by jeonhuhuhu** [comment]
Thank you so much for the quick reply. 

What we are curious about is what `perFrameIntrinsicCoeffs` and `K` values ​​are and how to get them. 

<img src="https://github.com/user-attachments/assets/c5ee5b02-8618-468d-9254-b2f26b460f71" width="70%">

From our understanding, the `K` value in the left image can be obtained from the `intrinsic_mat function` as follows. 
Is this correct? 

<img src="https://github.com/user-attachments/assets/a6d7f8bc-f1a0-4986-94e9-6e2c51c42925" width="70%">

`intrinsic_mat = self.get_intrinsic_mat_from_coeffs(self.session.get_intrinsic_mat())`

And I am wondering how can I get the `perFrameIntrinsicCoeffs` value in the right image. 

Additionally, I would appreciate it if you could tell me what the correlation is between the `K` value and the `perFrameIntrinsicCoeffs` value.

Are `perFrameIntrinsicCoeffs` and `K` the same data? 

I want to know exactly what kind of car it is, what it means, and how to get it

**Comment by marek-simonik** [comment]
The `K` matrix is the intrinsic matrix for the RGB camera of **the first frame** of a 3D video. The matrix `K` is therefore constructed from the same coefficients that are stored in `perFrameIntrinsicCoeffs[0]`.

In other words, `K` is redundant inside the `metadata` file, because all intrinsic coefficients are already stored in `perFrameIntrinsicCoeffs`. `K` is stored in the `metadata` file for historic reasons; Record3D was released in 2019 when the selfie FaceID camera did not have autofocus and when there was no LiDAR camera, so it did not make sense to store intrinsic coefficients for each frame (because the coefficients would be the same for each frame). Due to introduction of LiDAR and autofocus for the selfie FaceID camera, I added the `perFrameIntrinsicCoeffs` into the `metadata` file while keeping `K` for legacy reasons.

### Answering your questions regarding the camera's intrinsic coefficients:


> From our understanding, the K value in the left image can be obtained from the intrinsic_mat function as follows.
Is this correct?

Yes, that is correct.

> Additionally, I would appreciate it if you could tell me what the correlation is between the K value and the perFrameIntrinsicCoeffs value. Are perFrameIntrinsicCoeffs and K the same data?

This is explained in more detail above; `K` is the intrinsic matrix constructed from the 4 camera intrinsic coefficients `(fx, fy, tx, ty)` of the first frame. So yes, `perFrameIntrinsicCoeffs[0]` and `K` contain the same data (the 3x3 matrix `K` is constructed from the 4 intrinsic coefficients [like this](https://github.com/marek-simonik/record3d/blob/0c6e7692da100aad2d5195e307f01e75427a6a2a/demo-main.py#L40-L43), as you correctly said.

> And I am wondering how can I get the perFrameIntrinsicCoeffs value in the right image.

In the `demo-main.py` file, `self.session.get_intrinsic_mat()` returns the 4 camera intrinsic coefficients `(fx, fy, tx, ty)` for the current RGB image of the live stream. Those are the 4 intrinsic coefficients that should be stored per-frame into the `perFrameIntrinsicCoeffs` array of arrays. Apologies for the confusing name of the function; it would be less confusing if it was called `get_intrinsic_coeffs()`.

<hr>

### Regarding your test scenario:

I apologize, but I am not sure if I am able to help with your test that you described. It sounds to me like you wish to re-render a 4-5 second point cloud sequence (which was recorded from the camera pose A) from the viewpoint of the camera B — i.e. it sounds like you want to take a video recorded from the viewpoint of A, but transform it so that it looks as if it was recorded from the viewpoint of B (I understood it as if the RGBD images captured from the viewpoint of B were irrelevant for your purposes, and as if you were only interested in obtaining the camera pose at the viewpoint B so that you could re-render the RGBD data captured at A as if they were viewed from B's perspective).

In order to achieve this in Record3D, you would probably need to re-render the depth images and RGB images of the 4-5 second clip to match the point cloud that would be visible from the viewpoint of B. But I am not sure if I understood your question correctly.

**Comment by jeonhuhuhu** [comment]
> The `K` matrix is the intrinsic matrix for the RGB camera of **the first frame** of a 3D video. The matrix `K` is therefore constructed from the same coefficients that are stored in `perFrameIntrinsicCoeffs[0]`.
> 
> In other words, `K` is redundant inside the `metadata` file, because all intrinsic coefficients are already stored in `perFrameIntrinsicCoeffs`. `K` is stored in the `metadata` file for historic reasons; Record3D was released in 2019 when the selfie FaceID camera did not have autofocus and when there was no LiDAR camera, so it did not make sense to store intrinsic coefficients for each frame (because the coefficients would be the same for each frame). Due to introduction of LiDAR and autofocus for the selfie FaceID camera, I added the `perFrameIntrinsicCoeffs` into the `metadata` file while keeping `K` for legacy reasons.
> 
> ### Answering your questions regarding the camera's intrinsic coefficients:
> > From our understanding, the K value in the left image can be obtained from the intrinsic_mat function as follows.
> > Is this correct?
> 
> Yes, that is correct.
> 
> > Additionally, I would appreciate it if you could tell me what the correlation is between the K value and the perFrameIntrinsicCoeffs value. Are perFrameIntrinsicCoeffs and K the same data?
> 
> This is explained in more detail above; `K` is the intrinsic matrix constructed from the 4 camera intrinsic coefficients `(fx, fy, tx, ty)` of the first frame. So yes, `perFrameIntrinsicCoeffs[0]` and `K` contain the same data (the 3x3 matrix `K` is constructed from the 4 intrinsic coefficients [like this](https://github.com/marek-simonik/record3d/blob/0c6e7692da100aad2d5195e307f01e75427a6a2a/demo-main.py#L40-L43), as you correctly said.
> 
> > And I am wondering how can I get the perFrameIntrinsicCoeffs value in the right image.
> 
> In the `demo-main.py` file, `self.session.get_intrinsic_mat()` returns the 4 camera intrinsic coefficients `(fx, fy, tx, ty)` for the current RGB image of the live stream. Those are the 4 intrinsic coefficients that should be stored per-frame into the `perFrameIntrinsicCoeffs` array of arrays. Apologies for the confusing name of the function; it would be less confusing if it was called `get_intrinsic_coeffs()`.
> 
> ### Regarding your test scenario:
> I apologize, but I am not sure if I am able to help with your test that you described. It sounds to me like you wish to re-render a 4-5 second point cloud sequence (which was recorded from the camera pose A) from the viewpoint of the camera B — i.e. it sounds like you want to take a video recorded from the viewpoint of A, but transform it so that it looks as if it was recorded from the viewpoint of B (I understood it as if the RGBD images captured from the viewpoint of B were irrelevant for your purposes, and as if you were only interested in obtaining the camera pose at the viewpoint B so that you could re-render the RGBD data captured at A as if they were viewed from B's perspective).
> 
> In order to achieve this in Record3D, you would probably need to re-render the depth images and RGB images of the 4-5 second clip to match the point cloud that would be visible from the viewpoint of B. But I am not sure if I understood your question correctly.

The Record3D app you developed is very useful and I appreciate it.

That's fully answered, thank you!
